@startuml

class Mobile {

    - capacidadBateria : double
    # bateriaRestante : double

    + Mobile(double capacidadBateria)
    + bateria() : double
    + recargar() : void
    +  duracionTotalDeLlamadas() : Minuto

    # estaApagado() : boolean

}

class Registro {

    + void registrar(Minuto duracion)
    + Minuto duracionTotal()
}

class Personal {

    + registrar(iPhone : iPhone) : iPhone
    + recaudacion() : double

    - calcularTotalPrecioPorFraccion( fracciones : Array<Minuto>) : double
}

class Movistar {

    + registrar(motoG : MotoG) : iPhone
    + recaudacion() : double

}
Mobile *-- Registro

Personal o- Mobile
Mobile -o Movistar
@enduml